apiVersion: v1
kind: Service
metadata:
  name: mailcrab
  labels:
    app: mailcrab
spec:
  selector:
    app: mailcrab
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 1080
      name: http
    - protocol: TCP
      port: 1025
      targetPort: 1025
      name: smtp
  type: ClusterIP