# application-k8s.yml
spring:
  profiles: k8s
  kafka:
    bootstrap-servers: kafka-0.kafka-headless.default.svc.cluster.local:9092
  mail:
    host: mailcrab
    port: 1025

# You can override or add any other k8s-specific properties here
